version: '3.8'

services:
  mongodb:
    image: mongodb:latest
    container_name: mongodb
    restart: unless-stopped
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: root
    networks:
      - pi_network
    volumes:
      - mongo_data:/data/db

  backend:
    image: program-runner:latest
    container_name: backend
    restart: unless-stopped
    ports:
      - "8080:8080"
    networks:
      - pi_network
    devices:
      - "/dev/hidg0:/dev/hidg0"
      - "/dev/video0:/dev/video0"
      - "/dev/video1:/dev/video1"
    privileged: true

  frontend:
    image: webui:latest
    container_name: frontend
    restart: unless-stopped
    ports:
      - "3000:3000"
    networks:
      - pi_network
    depends_on:
      - mongodb
      - backend

volumes:
  mongo_data:

networks:
  pi_network:
    driver: bridge