name: Program Runner
on:
  push:
    branches:
      - master
    pull_request:
      branches:
        - master

env:
  REPO_ROOT: ${{ github.workspace }}

jobs:
  build-image:
    name: Build Program Runner Docker Image
    runs-on: ubuntu-22.04
    outputs:
      image: ${{ steps.build.outputs.image }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          submodules: recursive
          fetch-depth: 0

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build Docker Image
        id: build
        run: |
          IMAGE_NAME=program-runner:test
          docker build -f $REPO_ROOT/program-runner/build/program-runner.Dockerfile \
          -t $IMAGE_NAME $REPO_ROOT/program-runner/
          echo "image=$IMAGE_NAME" >> $GITHUB_OUTPUT

  test-image:
    name: Test Image
    runs-on: ubuntu-22.04
    needs: build-image
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          submodules: recursive
          fetch-depth: 0

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Run container
        run: |
          IMAGE_NAME=${{ needs.build-image.outputs.image }}
          # Run container detached
          docker run -d --name test-runner -p 8080:8080 $IMAGE_NAME
          sleep 5

      - name: Test /program/start
        run : |
          RESPONSE=$(curl -s -X POST http://localhost:8080/program/start \
          -H "Content-Type: application/json" \
          -d '{
            "programName": "Test",
            "displayName": "Test",
            "description": "Test Program, exits instantly",
            "category": "Tests",
            "settings": [
              {
                "argName": "waitTime",
                "displayName": "Wait Time",
                "value": 10
              },
              {
                "argName": "testString",
                "displayName": "Test String",
                "value": "Testing..."
              }
            ]
          }')

          echo "Response: $RESPONSE"
  
          if [ "$RESPONSE" != '{"status":"started"}' ]; then
            echo "Test failed"
            exit 1
          fi

      - name: Stop container
        run: |
          docker stop test-runner
          docker rm test-runner